installlanguage: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
  - apt-get install libopenblas-base

script:
  - ./_build.sh
  - ./_deploy.sh
